language: go

go:
  - "1.23"

os:
  - linux

dist: jammy

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go build -v .

after_success:
  - if [ -f coverage.txt ]; then bash <(curl -s https://codecov.io/bash) || true; fi

notifications:
  email:
    on_success: never
    on_failure: change
